[project]
name = "mebelink"
version = "1.0"
description = "Mobile app for furniture management"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flet>=0.85.3",
    "pydantic>=2.13.4",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "flet-desktop>=0.86.5",
    "mypy>=2.1.0",
    "pytest>=9.1.1",
    "rich>=15.0.0",
    "ruff>=0.16.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
exclude = ["build/"]

[tool.ruff.lint]
extend-select = ["W293"]

[tool.flet]
product = 'МебеЛинк'
app.exclude = [
    ".mypy_cache",
    ".pytest_cache",
    ".venv",
    ".git",
    "logs",
    "tests",
    ".gitignore",
    ".python-version",
    "data.db",
    # "pyproject.toml",
    # "uv.lock"
]

[tool.flet.splash]
android = false
