[project]
name = "mebelink"
version = "1.1"
description = "Mobile app for furniture project management"
readme = "README.md"
authors = [
    { name = "d1_boy4h", email = "d1.boy4h@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "flet>=0.85.3",
    "pydantic>=2.13.4",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "flet-desktop>=0.86.5",
    "mypy>=2.1.0",
    "pytest>=9.1.1",
    "rich>=15.0.0",
    "ruff>=0.16.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
exclude = ["build/"]

[tool.ruff.lint]
extend-select = ["W293"]

[tool.flet]
product = 'МебеЛинк'
app.exclude = [
    ".mypy_cache",
    ".pytest_cache",
    ".venv",
    ".git",
    "build",
    "logs",
    "tests",
    ".gitignore",
    ".python-version",
    "data.db",
    "screenshot.png",
    "README.md"
]

[tool.flet.splash]
color = "#ffffff"
dark_color = "#ffffff"

[tool.flet.boot_screen.flet]
theme_mode = "light"
bgcolor_light = "#ffffff"
spinner_color_light = "#4e78ef"
spinner_size = 30
text_color_light = "#000000"

[tool.flet.android]
target_arch = ['arm64-v8a']
