#:import hex kivy.utils.get_color_from_hex

#:import ProjectsScreen src.ui.screen

#:import Header src.ui.widgets
#:import ProjectsList src.ui.widgets
#:import ProjectsListElement src.ui.widgets

<Header>:
    padding: dp(10)

    size_hint_y: None
    height: logo.height + self.padding[1] * 2

    logo: logo

    canvas.before:
        Color:
            rgb: hex('#0096c7')
        
        Rectangle:
            size: self.size
            pos: self.pos

    Label:
        id: logo
        text: 'MebeLink'

        color: hex('#ffffff')
        font_size: sp(32)

        size_hint: None, None
        size: self.texture_size

<ProjectsList>:
    do_scroll_x: False
    projects_list_wrapper: projects_list_wrapper # self.projects_list_wrapper
    pos_hint: {'bottom': 0}

    canvas.before:
        Color:
            rgb: hex('#ffffff')
        
        Rectangle:
            size: self.size
            pos: self.pos

    BoxLayout:
        id: projects_list_wrapper
        orientation: 'vertical'
        size_hint_y: None
        height: self.minimum_height

<ProjectsListElement>:
    text: self.project_title
    height: dp(50)
    font_size: sp(20)

    size_hint_y: None
    size: self.texture_size
    padding: dp(15), dp(10), dp(10), dp(20)
    text_size: self.size

<ProjectsScreen>:
    name: 'projects_screen'

    projects_list: projects_list

    BoxLayout:
        orientation: 'vertical'

        Header
        ProjectsList:
            id: projects_list

ScreenManager:
    ProjectsScreen
